//
//  FIFontAwesomeIcon.h
//  FontasticIcons
//
//  Created by Alex Denisov on 17.11.12.
//  Copyright (c) 2012 Alex Denisov. All rights reserved.
//

#import "FIIcon.h"

@interface FIFontAwesomeIcon : FIIcon

+ (FIIcon *)glassIcon;
+ (FIIcon *)musicIcon;
+ (FIIcon *)searchIcon;
/*! @deprecated in 0.3.0. Use envelopeIcon instead. */+ (FIIcon *)mailIcon DEPRECATED_ATTRIBUTE;
+ (FIIcon *)envelopeIcon;
/*! @deprecated in 0.3.0. Use envelopeAltIcon instead. */+ (FIIcon *)mailAltIcon DEPRECATED_ATTRIBUTE;
+ (FIIcon *)envelopeAltIcon;
+ (FIIcon *)heartIcon;
+ (FIIcon *)heartEmptyIcon;
+ (FIIcon *)starIcon;
+ (FIIcon *)starEmptyIcon;
+ (FIIcon *)starHalfIcon;
+ (FIIcon *)userIcon;
/*! @deprecated in 0.3.0. Use groupIcon instead. */+ (FIIcon *)usersIcon DEPRECATED_ATTRIBUTE;
+ (FIIcon *)groupIcon;
+ (FIIcon *)userMdIcon;
/*! @deprecated in 0.3.0. Use filmIcon instead. */+ (FIIcon *)videoIcon DEPRECATED_ATTRIBUTE;
+ (FIIcon *)filmIcon;
/*! @deprecated in 0.3.0. Use facetimeVideoIcon instead. */+ (FIIcon *)videocamIcon DEPRECATED_ATTRIBUTE;
+ (FIIcon *)facetimeVideoIcon;
+ (FIIcon *)pictureIcon;
+ (FIIcon *)cameraIcon;
/*! @deprecated in 0.3.0. Use cameraRetroIcon instead. */+ (FIIcon *)cameraAltIcon DEPRECATED_ATTRIBUTE;
+ (FIIcon *)cameraRetroIcon;
+ (FIIcon *)thLargeIcon;
+ (FIIcon *)thIcon;
+ (FIIcon *)thListIcon;
+ (FIIcon *)okIcon;
+ (FIIcon *)okSignIcon;
/*! @deprecated in 0.3.0. Use okCircleIcon instead. */+ (FIIcon *)okCircle2Icon DEPRECATED_ATTRIBUTE;
/*! @seealso renamed okSignIcon in 0.3.0 */+ (FIIcon *)okCircleIcon;
/*! @deprecated in 0.3.0. Use removeIcon instead. */+ (FIIcon *)cancelIcon DEPRECATED_ATTRIBUTE;
+ (FIIcon *)removeIcon;
/*! @deprecated in 0.3.0. Use removeCircleIcon instead. */+ (FIIcon *)cancelCircleIcon DEPRECATED_ATTRIBUTE;
+ (FIIcon *)removeCircleIcon;
/*! @deprecated in 0.3.0. Use removeSignIcon instead. */+ (FIIcon *)cancelCircle2Icon DEPRECATED_ATTRIBUTE;
+ (FIIcon *)removeSignIcon;
+ (FIIcon *)plusIcon;
/*! @deprecated in 0.3.0. Use plusSignIcon instead. */+ (FIIcon *)plusCircleIcon DEPRECATED_ATTRIBUTE;
+ (FIIcon *)plusSignIcon;
+ (FIIcon *)minusIcon;
/*! @deprecated in 0.3.0. Use minusSignIcon instead. */+ (FIIcon *)minusCircleIcon DEPRECATED_ATTRIBUTE;
+ (FIIcon *)minusSignIcon;
/*! @deprecated in 0.3.0. Use questionSignIcon instead. */+ (FIIcon *)helpCircleIcon DEPRECATED_ATTRIBUTE;
+ (FIIcon *)questionSignIcon;
/*! @deprecated in 0.3.0. Use infoSignIcon instead. */+ (FIIcon *)infoCircleIcon DEPRECATED_ATTRIBUTE;
+ (FIIcon *)infoSignIcon;
+ (FIIcon *)homeIcon;
+ (FIIcon *)linkIcon;
/*! @deprecated in 0.3.0. Use externalLinkIcon instead. */+ (FIIcon *)linkExtIcon DEPRECATED_ATTRIBUTE;
+ (FIIcon *)externalLinkIcon;
/*! @deprecated in 0.3.0. Use paperClipIcon instead. */+ (FIIcon *)attachIcon DEPRECATED_ATTRIBUTE;
+ (FIIcon *)paperClipIcon;
+ (FIIcon *)lockIcon;
/*! @deprecated in 0.3.0. Use unlockIcon instead. */+ (FIIcon *)lockOpenIcon DEPRECATED_ATTRIBUTE;
+ (FIIcon *)unlockIcon;
/*! @deprecated in 0.3.0. Use pushpinIcon instead. */+ (FIIcon *)pinIcon DEPRECATED_ATTRIBUTE;
+ (FIIcon *)pushpinIcon;
/*! @deprecated in 0.3.0. Use eyeOpenIcon instead. */+ (FIIcon *)eyeIcon DEPRECATED_ATTRIBUTE;
+ (FIIcon *)eyeOpenIcon;
/*! @deprecated in 0.3.0. Use eyeCloseIcon instead. */+ (FIIcon *)eyeOffIcon DEPRECATED_ATTRIBUTE;
+ (FIIcon *)eyeCloseIcon;
+ (FIIcon *)tagIcon;
+ (FIIcon *)tagsIcon;
+ (FIIcon *)bookmarkIcon;
+ (FIIcon *)bookmarkEmptyIcon;
+ (FIIcon *)flagIcon;
+ (FIIcon *)thumbsUpIcon;
+ (FIIcon *)thumbsDownIcon;
+ (FIIcon *)downloadAltIcon;
+ (FIIcon *)uploadAltIcon;
+ (FIIcon *)shareAltIcon;
/*! @deprecated in 0.3.0. Use shareIcon instead. */+ (FIIcon *)exportIcon DEPRECATED_ATTRIBUTE;
+ (FIIcon *)shareIcon;
+ (FIIcon *)pencilIcon;
+ (FIIcon *)editIcon;
+ (FIIcon *)printIcon;
+ (FIIcon *)retweetIcon;
/*! @seealso renamed commentAltIcon in 0.3.0 */+ (FIIcon *)commentIcon;
+ (FIIcon *)commentsIcon;
+ (FIIcon *)commentAltIcon;
/*! @deprecated in 0.3.0. Use commentsAltIcon instead. */+ (FIIcon *)chatIcon DEPRECATED_ATTRIBUTE;
+ (FIIcon *)commentsAltIcon;
+ (FIIcon *)bellIcon;
/*! @deprecated in 0.3.0. Use warningSignIcon instead. */+ (FIIcon *)attentionIcon DEPRECATED_ATTRIBUTE;
+ (FIIcon *)warningSignIcon;
/*! @deprecated in 0.3.0. Use exclamationSignIcon instead. */+ (FIIcon *)attentionCircleIcon DEPRECATED_ATTRIBUTE;
+ (FIIcon *)exclamationSignIcon;
/*! @deprecated in 0.3.0. Use mapMarkerIcon instead. */+ (FIIcon *)locationIcon DEPRECATED_ATTRIBUTE;
+ (FIIcon *)mapMarkerIcon;
+ (FIIcon *)trashIcon;
/*! @deprecated in 0.3.0. Use fileIcon instead. */+ (FIIcon *)docIcon DEPRECATED_ATTRIBUTE;
+ (FIIcon *)fileIcon;
/*! @deprecated in 0.3.0. Use copyIcon instead. */+ (FIIcon *)docsIcon DEPRECATED_ATTRIBUTE;
+ (FIIcon *)copyIcon;
/*! @deprecated in 0.3.0. Use folderCloseIcon instead. */+ (FIIcon *)folderIcon DEPRECATED_ATTRIBUTE;
+ (FIIcon *)folderCloseIcon;
+ (FIIcon *)folderOpenIcon;
+ (FIIcon *)rssIcon;
+ (FIIcon *)phoneIcon;
/*! @deprecated in 0.3.0. Use  phoneSignIcon. */+ (FIIcon *)phoneSquaredIcon DEPRECATED_ATTRIBUTE;
+ (FIIcon *)phoneSignIcon;
/*! @deprecated in 0.3.0. Use reorderIcon instead. */+ (FIIcon *)menuIcon DEPRECATED_ATTRIBUTE;
+ (FIIcon *)reorderIcon;
+ (FIIcon *)cogIcon;
/*! @deprecated in 0.3.0. Use cogsIcon instead. */+ (FIIcon *)cogAltIcon DEPRECATED_ATTRIBUTE;
+ (FIIcon *)cogsIcon;
+ (FIIcon *)wrenchIcon;
/*! @deprecated in 0.3.0. Use shoppingCartIcon instead. */+ (FIIcon *)basketIcon DEPRECATED_ATTRIBUTE;
+ (FIIcon *)shoppingCartIcon;
+ (FIIcon *)calendarIcon;
/*! @deprecated in 0.3.0. Use signinIcon instead. */+ (FIIcon *)loginIcon DEPRECATED_ATTRIBUTE;
+ (FIIcon *)signinIcon;
/*! @deprecated in 0.3.0. Use signoutIcon instead. */+ (FIIcon *)logoutIcon DEPRECATED_ATTRIBUTE;
+ (FIIcon *)signoutIcon;
+ (FIIcon *)volumeOffIcon;
+ (FIIcon *)volumeDownIcon;
+ (FIIcon *)volumeUpIcon;
+ (FIIcon *)headphonesIcon;
/*! @deprecated in 0.3.0. Use timeIcon instead. */+ (FIIcon *)clockIcon DEPRECATED_ATTRIBUTE;
+ (FIIcon *)timeIcon;
/*! @deprecated in 0.3.0. Use banCircleIcon instead. */+ (FIIcon *)blockIcon DEPRECATED_ATTRIBUTE;
+ (FIIcon *)banCircleIcon;
+ (FIIcon *)resizeFullIcon;
/*! @deprecated in 0.3.0. Use fullscreenIcon instead. */+ (FIIcon *)resizeFullAltIcon DEPRECATED_ATTRIBUTE;
+ (FIIcon *)fullscreenIcon;
+ (FIIcon *)resizeSmallIcon;
+ (FIIcon *)resizeVerticalIcon;
+ (FIIcon *)resizeHorizontalIcon;
+ (FIIcon *)moveIcon;
+ (FIIcon *)zoomInIcon;
+ (FIIcon *)zoomOutIcon;
/*! @deprecated in 0.3.0. Use downloadIcon instead. */+ (FIIcon *)downCircle2Icon DEPRECATED_ATTRIBUTE;
/*! @seealso downloadAltIcon renamed in 0.3.0 */+ (FIIcon *)downloadIcon;
/*! @deprecated in 0.3.0. Use uploadIcon instead. */+ (FIIcon *)upCircle2Icon DEPRECATED_ATTRIBUTE;
/*! @seealso uploadAltIcon renamed in 0.3.0 */+ (FIIcon *)uploadIcon;
/*! @deprecated in 0.3.0. Use caretDownIcon instead. */+ (FIIcon *)downDirIcon DEPRECATED_ATTRIBUTE;
+ (FIIcon *)caretDownIcon;
/*! @deprecated in 0.3.0. Use caretUpIcon instead. */+ (FIIcon *)upDirIcon DEPRECATED_ATTRIBUTE;
+ (FIIcon *)caretUpIcon;
/*! @deprecated in 0.3.0. Use caretLeftIcon instead. */+ (FIIcon *)leftDirIcon DEPRECATED_ATTRIBUTE;
+ (FIIcon *)caretLeftIcon;
/*! @deprecated in 0.3.0. Use caretRightIcon instead. */+ (FIIcon *)rightDirIcon DEPRECATED_ATTRIBUTE;
+ (FIIcon *)caretRightIcon;
/*! @deprecated in 0.3.0. Use chevronDownIcon instead. */+ (FIIcon *)downOpenIcon DEPRECATED_ATTRIBUTE;
+ (FIIcon *)chevronDownIcon;
/*! @deprecated in 0.3.0. Use chevronLeftIcon instead. */+ (FIIcon *)leftOpenIcon DEPRECATED_ATTRIBUTE;
+ (FIIcon *)chevronLeftIcon;
/*! @deprecated in 0.3.0. Use chevronRightIcon instead. */+ (FIIcon *)rightOpenIcon DEPRECATED_ATTRIBUTE;
+ (FIIcon *)chevronRightIcon;
/*! @deprecated in 0.3.0. Use chevronUpIcon instead. */+ (FIIcon *)upOpenIcon DEPRECATED_ATTRIBUTE;
+ (FIIcon *)chevronUpIcon;
/*! @deprecated in 0.3.0. Use arrowDownIcon instead. */+ (FIIcon *)downIcon DEPRECATED_ATTRIBUTE;
+ (FIIcon *)arrowDownIcon;
/*! @deprecated in 0.3.0. Use arrowLeftIcon instead. */+ (FIIcon *)leftIcon DEPRECATED_ATTRIBUTE;
+ (FIIcon *)arrowLeftIcon;
/*! @deprecated in 0.3.0. Use arrowRightIcon instead. */+ (FIIcon *)rightIcon DEPRECATED_ATTRIBUTE;
+ (FIIcon *)arrowRightIcon;
/*! @deprecated in 0.3.0. Use arrowUpIcon instead. */+ (FIIcon *)upIcon DEPRECATED_ATTRIBUTE;
+ (FIIcon *)arrowUpIcon;
/*! @deprecated in 0.3.0. Use handRightIcon instead. */+ (FIIcon *)rightHandIcon DEPRECATED_ATTRIBUTE;
+ (FIIcon *)handRightIcon;
/*! @deprecated in 0.3.0. Use handLeftIcon instead. */+ (FIIcon *)leftHandIcon DEPRECATED_ATTRIBUTE;
+ (FIIcon *)handLeftIcon;
/*! @deprecated in 0.3.0. Use handUpIcon instead. */+ (FIIcon *)upHandIcon DEPRECATED_ATTRIBUTE;
+ (FIIcon *)handUpIcon;
/*! @deprecated in 0.3.0. Use handDownIcon instead. */+ (FIIcon *)downHandIcon DEPRECATED_ATTRIBUTE;
+ (FIIcon *)handDownIcon;
/*! @deprecated in 0.3.0. Use circleArrowLeftIcon instead. */+ (FIIcon *)leftCircledIcon DEPRECATED_ATTRIBUTE;
+ (FIIcon *)circleArrowLeftIcon;
/*! @deprecated in 0.3.0. Use circleArrowRightIcon instead. */+ (FIIcon *)rightCircledIcon DEPRECATED_ATTRIBUTE;
+ (FIIcon *)circleArrowRightIcon;
/*! @deprecated in 0.3.0. Use circleArrowUpIcon instead. */+ (FIIcon *)upCircledIcon DEPRECATED_ATTRIBUTE;
+ (FIIcon *)circleArrowUpIcon;
/*! @deprecated in 0.3.0. Use circleArrowDownIcon instead. */+ (FIIcon *)downCircledIcon DEPRECATED_ATTRIBUTE;
+ (FIIcon *)circleArrowDownIcon;
/*! @deprecated in 0.3.0. Use repeatIcon instead. */+ (FIIcon *)cwIcon DEPRECATED_ATTRIBUTE;
+ (FIIcon *)repeatIcon;
/*! @deprecated in 0.3.0. Use undoIcon instead. */+ (FIIcon *)ccwIcon DEPRECATED_ATTRIBUTE;
+ (FIIcon *)undoIcon;
/*! @deprecated in 0.3.0. Use refreshIcon instead. */+ (FIIcon *)arrowsCwIcon DEPRECATED_ATTRIBUTE;
+ (FIIcon *)refreshIcon;
/*! @deprecated in 0.3.0. Use randomIcon instead. */+ (FIIcon *)shuffleIcon DEPRECATED_ATTRIBUTE;
+ (FIIcon *)randomIcon;
+ (FIIcon *)playIcon;
/*! @deprecated in 0.3.0. Use playCircleIcon instead. */+ (FIIcon *)playCircle2Icon DEPRECATED_ATTRIBUTE;
+ (FIIcon *)playCircleIcon;
+ (FIIcon *)stopIcon;
+ (FIIcon *)pauseIcon;
/*! @deprecated in 0.3.0. Use stepForwardIcon instead. */+ (FIIcon *)toEndIcon DEPRECATED_ATTRIBUTE;
+ (FIIcon *)stepForwardIcon;
/*! @deprecated in 0.3.0. Use fastForwardIcon instead. */+ (FIIcon *)toEndAltIcon DEPRECATED_ATTRIBUTE;
+ (FIIcon *)fastForwardIcon;
/*! @deprecated in 0.3.0. Use stepBackwardIcon instead. */+ (FIIcon *)toStartIcon DEPRECATED_ATTRIBUTE;
+ (FIIcon *)stepBackwardIcon;
/*! @deprecated in 0.3.0. Use fastBackwardIcon instead. */+ (FIIcon *)toStartAltIcon DEPRECATED_ATTRIBUTE;
+ (FIIcon *)fastBackwardIcon;
/*! @deprecated in 0.3.0. Use forwardIcon instead. */+ (FIIcon *)fastFwIcon DEPRECATED_ATTRIBUTE;
/*! @seealso renamed shareAltIcon in 0.3.0 */+ (FIIcon *)forwardIcon;
/*! @deprecated in 0.3.0. Use backwardIcon instead. */+ (FIIcon *)fastBwIcon DEPRECATED_ATTRIBUTE;
+ (FIIcon *)backwardIcon;
+ (FIIcon *)ejectIcon;
/*! @deprecated in 0.3.0. Use screenshotIcon instead. */+ (FIIcon *)targetIcon DEPRECATED_ATTRIBUTE;
+ (FIIcon *)screenshotIcon;
+ (FIIcon *)signalIcon;
/*! @deprecated in 0.3.0. Use trophyIcon instead. */+ (FIIcon *)awardIcon DEPRECATED_ATTRIBUTE;
+ (FIIcon *)trophyIcon;
+ (FIIcon *)inboxIcon;
+ (FIIcon *)globeIcon;
+ (FIIcon *)cloudIcon;
/*! @deprecated in 0.3.0. Use boltIcon instead. */+ (FIIcon *)flashIcon DEPRECATED_ATTRIBUTE;
+ (FIIcon *)boltIcon;
+ (FIIcon *)umbrellaIcon;
/*! @deprecated in 0.3.0. Use planeIcon instead. */+ (FIIcon *)flightIcon DEPRECATED_ATTRIBUTE;
+ (FIIcon *)planeIcon;
+ (FIIcon *)leafIcon;
+ (FIIcon *)fontIcon;
+ (FIIcon *)boldIcon;
+ (FIIcon *)italicIcon;
+ (FIIcon *)textHeightIcon;
+ (FIIcon *)textWidthIcon;
+ (FIIcon *)alignLeftIcon;
+ (FIIcon *)alignCenterIcon;
+ (FIIcon *)alignRightIcon;
+ (FIIcon *)alignJustifyIcon;
+ (FIIcon *)listIcon;
+ (FIIcon *)indentLeftIcon;
+ (FIIcon *)indentRightIcon;
/*! @deprecated in 0.3.0. Use listUlIcon instead. */+ (FIIcon *)listBulletIcon DEPRECATED_ATTRIBUTE;
+ (FIIcon *)listUlIcon;
/*! @deprecated in 0.3.0. Use listOlIcon instead. */+ (FIIcon *)listNumberedIcon DEPRECATED_ATTRIBUTE;
+ (FIIcon *)listOlIcon;
/*! @deprecated in 0.3.0. Use strikethroughIcon instead. */+ (FIIcon *)strikeIcon DEPRECATED_ATTRIBUTE;
+ (FIIcon *)strikethroughIcon;
+ (FIIcon *)underlineIcon;
+ (FIIcon *)tableIcon;
+ (FIIcon *)columnsIcon;
/*! @deprecated in 0.3.0. Use cutIcon instead. */+ (FIIcon *)scissorsIcon DEPRECATED_ATTRIBUTE;
+ (FIIcon *)cutIcon;
+ (FIIcon *)pasteIcon;
+ (FIIcon *)briefcaseIcon;
+ (FIIcon *)offIcon;
+ (FIIcon *)roadIcon;
+ (FIIcon *)listAltIcon;
+ (FIIcon *)qrcodeIcon;
+ (FIIcon *)barcodeIcon;
+ (FIIcon *)bookIcon;
/*! @deprecated in 0.3.0. Use adjustIcon instead. */+ (FIIcon *)ajustIcon DEPRECATED_ATTRIBUTE;
+ (FIIcon *)adjustIcon;
+ (FIIcon *)tintIcon;
+ (FIIcon *)checkIcon;
+ (FIIcon *)checkEmptyIcon;
+ (FIIcon *)asteriskIcon;
+ (FIIcon *)giftIcon;
+ (FIIcon *)fireIcon;
+ (FIIcon *)magnetIcon;
/*! @deprecated in 0.3.0. Use barChartIcon instead. */+ (FIIcon *)chartBarIcon DEPRECATED_ATTRIBUTE;
+ (FIIcon *)barChartIcon;
+ (FIIcon *)creditCardIcon;
/*! @deprecated in 0.3.0. Use saveIcon instead. */+ (FIIcon *)floppyIcon DEPRECATED_ATTRIBUTE;
+ (FIIcon *)saveIcon;
/*! @deprecated in 0.3.0. Use bullhornIcon instead. */+ (FIIcon *)megaphoneIcon DEPRECATED_ATTRIBUTE;
+ (FIIcon *)bullhornIcon;
+ (FIIcon *)hddIcon;
+ (FIIcon *)keyIcon;
+ (FIIcon *)certificateIcon;
+ (FIIcon *)tasksIcon;
+ (FIIcon *)filterIcon;
+ (FIIcon *)beakerIcon;
+ (FIIcon *)magicIcon;
+ (FIIcon *)truckIcon;
+ (FIIcon *)moneyIcon;
+ (FIIcon *)sortIcon;
+ (FIIcon *)sortDownIcon;
+ (FIIcon *)sortUpIcon;
/*! @deprecated in 0.3.0. Use legalIcon instead. */+ (FIIcon *)hammerIcon DEPRECATED_ATTRIBUTE;
+ (FIIcon *)legalIcon;
+ (FIIcon *)gaugeIcon;
+ (FIIcon *)sitemapIcon;
/*! @deprecated in 0.3.0. Use githubSignIcon instead. */+ (FIIcon *)githubSquaredIcon DEPRECATED_ATTRIBUTE;
+ (FIIcon *)githubSignIcon;
+ (FIIcon *)githubIcon;
/*! @deprecated in 0.3.0. Use twitterSignIcon instead. */+ (FIIcon *)twitterSquaredIcon DEPRECATED_ATTRIBUTE;
+ (FIIcon *)twitterSignIcon;
+ (FIIcon *)twitterIcon;
/*! @deprecated in 0.3.0. Use facebookSignIcon instead. */+ (FIIcon *)facebookSquaredIcon DEPRECATED_ATTRIBUTE;
+ (FIIcon *)facebookSignIcon;
+ (FIIcon *)facebookIcon;
/*! @deprecated in 0.3.0. Use linkedinSignIcon instead. */+ (FIIcon *)linkedinSquaredIcon DEPRECATED_ATTRIBUTE;
+ (FIIcon *)linkedinSignIcon;
+ (FIIcon *)linkedinIcon;
/*! @deprecated in 0.3.0. Use pinterestIcon instead. */+ (FIIcon *)pinterestCircledIcon DEPRECATED_ATTRIBUTE;
+ (FIIcon *)pinterestIcon;
/*! @deprecated in 0.3.0. Use pinterestSignIcon instead. */+ (FIIcon *)pinterestSquaredIcon DEPRECATED_ATTRIBUTE;
+ (FIIcon *)pinterestSignIcon;
/*! @deprecated in 0.3.0. Use googlePlusSignIcon instead. */+ (FIIcon *)gplusSquaredIcon DEPRECATED_ATTRIBUTE;
+ (FIIcon *)googlePlusSignIcon;
/*! @deprecated in 0.3.0. Use googlePlusIcon instead. */+ (FIIcon *)gplusIcon DEPRECATED_ATTRIBUTE;
+ (FIIcon *)googlePlusIcon;
/*! @deprecated in 0.3.0. Use signBlankIcon instead. */+ (FIIcon *)blankIcon DEPRECATED_ATTRIBUTE;
+ (FIIcon *)signBlankIcon;
+ (FIIcon *)lemonIcon;
@end
