//
//  FIFontAwesomeIcon.h
//  FontasticIcons
//
//  Created by Alex Denisov on 17.11.12.
//  Copyright (c) 2012 Alex Denisov. All rights reserved.
//

#import "FIIcon.h"

@interface FIFontAwesomeIcon : FIIcon
@end

@interface FIFontAwesomeIcon (Forwarding)

+ (instancetype)glassIcon;
+ (instancetype)musicIcon;
+ (instancetype)searchIcon;
+ (instancetype)envelopeIcon;
+ (instancetype)envelopeAltIcon;
+ (instancetype)heartIcon;
+ (instancetype)heartEmptyIcon;
+ (instancetype)starIcon;
+ (instancetype)starEmptyIcon;
+ (instancetype)starHalfIcon;
+ (instancetype)userIcon;
+ (instancetype)groupIcon;
+ (instancetype)userMdIcon;
+ (instancetype)filmIcon;
+ (instancetype)facetimeVideoIcon;
+ (instancetype)pictureIcon;
+ (instancetype)cameraIcon;
+ (instancetype)cameraRetroIcon;
+ (instancetype)thLargeIcon;
+ (instancetype)thIcon;
+ (instancetype)thListIcon;
+ (instancetype)okIcon;
+ (instancetype)okSignIcon;
/*! @seealso renamed okSignIcon in 0.3.0 */+ (instancetype)okCircleIcon;
+ (instancetype)removeIcon;
+ (instancetype)removeCircleIcon;
+ (instancetype)removeSignIcon;
+ (instancetype)plusIcon;
+ (instancetype)plusSignIcon;
+ (instancetype)minusIcon;
+ (instancetype)minusSignIcon;
+ (instancetype)questionSignIcon;
+ (instancetype)infoSignIcon;
+ (instancetype)homeIcon;
+ (instancetype)linkIcon;
+ (instancetype)externalLinkIcon;
+ (instancetype)paperClipIcon;
+ (instancetype)lockIcon;
+ (instancetype)unlockIcon;
+ (instancetype)pushpinIcon;
+ (instancetype)eyeOpenIcon;
+ (instancetype)eyeCloseIcon;
+ (instancetype)tagIcon;
+ (instancetype)tagsIcon;
+ (instancetype)bookmarkIcon;
+ (instancetype)bookmarkEmptyIcon;
+ (instancetype)flagIcon;
+ (instancetype)thumbsUpIcon;
+ (instancetype)thumbsDownIcon;
+ (instancetype)downloadAltIcon;
+ (instancetype)uploadAltIcon;
+ (instancetype)shareAltIcon;
+ (instancetype)shareIcon;
+ (instancetype)pencilIcon;
+ (instancetype)editIcon;
+ (instancetype)printIcon;
+ (instancetype)retweetIcon;
/*! @seealso renamed commentAltIcon in 0.3.0 */+ (instancetype)commentIcon;
+ (instancetype)commentsIcon;
+ (instancetype)commentAltIcon;
+ (instancetype)commentsAltIcon;
+ (instancetype)bellIcon;
+ (instancetype)warningSignIcon;
+ (instancetype)exclamationSignIcon;
+ (instancetype)mapMarkerIcon;
+ (instancetype)trashIcon;
+ (instancetype)fileIcon;
+ (instancetype)copyIcon;
+ (instancetype)folderCloseIcon;
+ (instancetype)folderOpenIcon;
+ (instancetype)rssIcon;
+ (instancetype)phoneIcon;
+ (instancetype)phoneSignIcon;
+ (instancetype)reorderIcon;
+ (instancetype)cogIcon;
+ (instancetype)cogsIcon;
+ (instancetype)wrenchIcon;
+ (instancetype)shoppingCartIcon;
+ (instancetype)calendarIcon;
+ (instancetype)signinIcon;
+ (instancetype)signoutIcon;
+ (instancetype)volumeOffIcon;
+ (instancetype)volumeDownIcon;
+ (instancetype)volumeUpIcon;
+ (instancetype)headphonesIcon;
+ (instancetype)timeIcon;
+ (instancetype)banCircleIcon;
+ (instancetype)resizeFullIcon;
+ (instancetype)fullscreenIcon;
+ (instancetype)resizeSmallIcon;
+ (instancetype)resizeVerticalIcon;
+ (instancetype)resizeHorizontalIcon;
+ (instancetype)moveIcon;
+ (instancetype)zoomInIcon;
+ (instancetype)zoomOutIcon;
/*! @seealso downloadAltIcon renamed in 0.3.0 */+ (instancetype)downloadIcon;
/*! @seealso uploadAltIcon renamed in 0.3.0 */+ (instancetype)uploadIcon;
+ (instancetype)caretDownIcon;
+ (instancetype)caretUpIcon;
+ (instancetype)caretLeftIcon;
+ (instancetype)caretRightIcon;
+ (instancetype)chevronDownIcon;
+ (instancetype)chevronLeftIcon;
+ (instancetype)chevronRightIcon;
+ (instancetype)chevronUpIcon;
+ (instancetype)arrowDownIcon;
+ (instancetype)arrowLeftIcon;
+ (instancetype)arrowRightIcon;
+ (instancetype)arrowUpIcon;
+ (instancetype)handRightIcon;
+ (instancetype)handLeftIcon;
+ (instancetype)handUpIcon;
+ (instancetype)handDownIcon;
+ (instancetype)circleArrowLeftIcon;
+ (instancetype)circleArrowRightIcon;
+ (instancetype)circleArrowUpIcon;
+ (instancetype)circleArrowDownIcon;
+ (instancetype)repeatIcon;
+ (instancetype)undoIcon;
+ (instancetype)refreshIcon;
+ (instancetype)randomIcon;
+ (instancetype)playIcon;
+ (instancetype)playCircleIcon;
+ (instancetype)stopIcon;
+ (instancetype)pauseIcon;
+ (instancetype)stepForwardIcon;
+ (instancetype)fastForwardIcon;
+ (instancetype)stepBackwardIcon;
+ (instancetype)fastBackwardIcon;
/*! @seealso renamed shareAltIcon in 0.3.0 */+ (instancetype)forwardIcon;
+ (instancetype)backwardIcon;
+ (instancetype)ejectIcon;
+ (instancetype)screenshotIcon;
+ (instancetype)signalIcon;
+ (instancetype)trophyIcon;
+ (instancetype)inboxIcon;
+ (instancetype)globeIcon;
+ (instancetype)cloudIcon;
+ (instancetype)boltIcon;
+ (instancetype)umbrellaIcon;
+ (instancetype)planeIcon;
+ (instancetype)leafIcon;
+ (instancetype)fontIcon;
+ (instancetype)boldIcon;
+ (instancetype)italicIcon;
+ (instancetype)textHeightIcon;
+ (instancetype)textWidthIcon;
+ (instancetype)alignLeftIcon;
+ (instancetype)alignCenterIcon;
+ (instancetype)alignRightIcon;
+ (instancetype)alignJustifyIcon;
+ (instancetype)listIcon;
+ (instancetype)indentLeftIcon;
+ (instancetype)indentRightIcon;
+ (instancetype)listUlIcon;
+ (instancetype)listOlIcon;
+ (instancetype)strikethroughIcon;
+ (instancetype)underlineIcon;
+ (instancetype)tableIcon;
+ (instancetype)columnsIcon;
+ (instancetype)cutIcon;
+ (instancetype)pasteIcon;
+ (instancetype)briefcaseIcon;
+ (instancetype)offIcon;
+ (instancetype)roadIcon;
+ (instancetype)listAltIcon;
+ (instancetype)qrcodeIcon;
+ (instancetype)barcodeIcon;
+ (instancetype)bookIcon;
+ (instancetype)adjustIcon;
+ (instancetype)tintIcon;
+ (instancetype)checkIcon;
+ (instancetype)checkEmptyIcon;
+ (instancetype)asteriskIcon;
+ (instancetype)giftIcon;
+ (instancetype)fireIcon;
+ (instancetype)magnetIcon;
+ (instancetype)barChartIcon;
+ (instancetype)creditCardIcon;
+ (instancetype)saveIcon;
+ (instancetype)bullhornIcon;
+ (instancetype)hddIcon;
+ (instancetype)keyIcon;
+ (instancetype)certificateIcon;
+ (instancetype)tasksIcon;
+ (instancetype)filterIcon;
+ (instancetype)beakerIcon;
+ (instancetype)magicIcon;
+ (instancetype)truckIcon;
+ (instancetype)moneyIcon;
+ (instancetype)sortIcon;
+ (instancetype)sortDownIcon;
+ (instancetype)sortUpIcon;
+ (instancetype)legalIcon;
+ (instancetype)gaugeIcon;
+ (instancetype)sitemapIcon;
+ (instancetype)githubSignIcon;
+ (instancetype)githubIcon;
+ (instancetype)twitterSignIcon;
+ (instancetype)twitterIcon;
+ (instancetype)facebookSignIcon;
+ (instancetype)facebookIcon;
+ (instancetype)linkedinSignIcon;
+ (instancetype)linkedinIcon;
+ (instancetype)pinterestIcon;
+ (instancetype)pinterestSignIcon;
+ (instancetype)googlePlusSignIcon;
+ (instancetype)googlePlusIcon;
+ (instancetype)signBlankIcon;
+ (instancetype)lemonIcon;

#pragma mark - Deprecated

/*! @deprecated in 0.3.0. Use envelopeIcon instead. */+ (instancetype)mailIcon DEPRECATED_ATTRIBUTE;
/*! @deprecated in 0.3.0. Use envelopeAltIcon instead. */+ (instancetype)mailAltIcon DEPRECATED_ATTRIBUTE;
/*! @deprecated in 0.3.0. Use groupIcon instead. */+ (instancetype)usersIcon DEPRECATED_ATTRIBUTE;
/*! @deprecated in 0.3.0. Use filmIcon instead. */+ (instancetype)videoIcon DEPRECATED_ATTRIBUTE;
/*! @deprecated in 0.3.0. Use facetimeVideoIcon instead. */+ (instancetype)videocamIcon DEPRECATED_ATTRIBUTE;
/*! @deprecated in 0.3.0. Use cameraRetroIcon instead. */+ (instancetype)cameraAltIcon DEPRECATED_ATTRIBUTE;
/*! @deprecated in 0.3.0. Use okCircleIcon instead. */+ (instancetype)okCircle2Icon DEPRECATED_ATTRIBUTE;
/*! @deprecated in 0.3.0. Use removeIcon instead. */+ (instancetype)cancelIcon DEPRECATED_ATTRIBUTE;
/*! @deprecated in 0.3.0. Use removeCircleIcon instead. */+ (instancetype)cancelCircleIcon DEPRECATED_ATTRIBUTE;
/*! @deprecated in 0.3.0. Use removeSignIcon instead. */+ (instancetype)cancelCircle2Icon DEPRECATED_ATTRIBUTE;
/*! @deprecated in 0.3.0. Use plusSignIcon instead. */+ (instancetype)plusCircleIcon DEPRECATED_ATTRIBUTE;
/*! @deprecated in 0.3.0. Use minusSignIcon instead. */+ (instancetype)minusCircleIcon DEPRECATED_ATTRIBUTE;
/*! @deprecated in 0.3.0. Use questionSignIcon instead. */+ (instancetype)helpCircleIcon DEPRECATED_ATTRIBUTE;
/*! @deprecated in 0.3.0. Use infoSignIcon instead. */+ (instancetype)infoCircleIcon DEPRECATED_ATTRIBUTE;
/*! @deprecated in 0.3.0. Use externalLinkIcon instead. */+ (instancetype)linkExtIcon DEPRECATED_ATTRIBUTE;
/*! @deprecated in 0.3.0. Use paperClipIcon instead. */+ (instancetype)attachIcon DEPRECATED_ATTRIBUTE;
/*! @deprecated in 0.3.0. Use unlockIcon instead. */+ (instancetype)lockOpenIcon DEPRECATED_ATTRIBUTE;
/*! @deprecated in 0.3.0. Use pushpinIcon instead. */+ (instancetype)pinIcon DEPRECATED_ATTRIBUTE;
/*! @deprecated in 0.3.0. Use eyeOpenIcon instead. */+ (instancetype)eyeIcon DEPRECATED_ATTRIBUTE;
/*! @deprecated in 0.3.0. Use eyeCloseIcon instead. */+ (instancetype)eyeOffIcon DEPRECATED_ATTRIBUTE;
/*! @deprecated in 0.3.0. Use shareIcon instead. */+ (instancetype)exportIcon DEPRECATED_ATTRIBUTE;
/*! @deprecated in 0.3.0. Use commentsAltIcon instead. */+ (instancetype)chatIcon DEPRECATED_ATTRIBUTE;
/*! @deprecated in 0.3.0. Use warningSignIcon instead. */+ (instancetype)attentionIcon DEPRECATED_ATTRIBUTE;
/*! @deprecated in 0.3.0. Use exclamationSignIcon instead. */+ (instancetype)attentionCircleIcon DEPRECATED_ATTRIBUTE;
/*! @deprecated in 0.3.0. Use mapMarkerIcon instead. */+ (instancetype)locationIcon DEPRECATED_ATTRIBUTE;
/*! @deprecated in 0.3.0. Use fileIcon instead. */+ (instancetype)docIcon DEPRECATED_ATTRIBUTE;
/*! @deprecated in 0.3.0. Use copyIcon instead. */+ (instancetype)docsIcon DEPRECATED_ATTRIBUTE;
/*! @deprecated in 0.3.0. Use folderCloseIcon instead. */+ (instancetype)folderIcon DEPRECATED_ATTRIBUTE;
/*! @deprecated in 0.3.0. Use  phoneSignIcon. */+ (instancetype)phoneSquaredIcon DEPRECATED_ATTRIBUTE;
/*! @deprecated in 0.3.0. Use reorderIcon instead. */+ (instancetype)menuIcon DEPRECATED_ATTRIBUTE;
/*! @deprecated in 0.3.0. Use cogsIcon instead. */+ (instancetype)cogAltIcon DEPRECATED_ATTRIBUTE;
/*! @deprecated in 0.3.0. Use shoppingCartIcon instead. */+ (instancetype)basketIcon DEPRECATED_ATTRIBUTE;
/*! @deprecated in 0.3.0. Use signinIcon instead. */+ (instancetype)loginIcon DEPRECATED_ATTRIBUTE;
/*! @deprecated in 0.3.0. Use signoutIcon instead. */+ (instancetype)logoutIcon DEPRECATED_ATTRIBUTE;
/*! @deprecated in 0.3.0. Use timeIcon instead. */+ (instancetype)clockIcon DEPRECATED_ATTRIBUTE;
/*! @deprecated in 0.3.0. Use banCircleIcon instead. */+ (instancetype)blockIcon DEPRECATED_ATTRIBUTE;
/*! @deprecated in 0.3.0. Use fullscreenIcon instead. */+ (instancetype)resizeFullAltIcon DEPRECATED_ATTRIBUTE;
/*! @deprecated in 0.3.0. Use downloadIcon instead. */+ (instancetype)downCircle2Icon DEPRECATED_ATTRIBUTE;
/*! @deprecated in 0.3.0. Use uploadIcon instead. */+ (instancetype)upCircle2Icon DEPRECATED_ATTRIBUTE;
/*! @deprecated in 0.3.0. Use caretDownIcon instead. */+ (instancetype)downDirIcon DEPRECATED_ATTRIBUTE;
/*! @deprecated in 0.3.0. Use caretUpIcon instead. */+ (instancetype)upDirIcon DEPRECATED_ATTRIBUTE;
/*! @deprecated in 0.3.0. Use caretLeftIcon instead. */+ (instancetype)leftDirIcon DEPRECATED_ATTRIBUTE;
/*! @deprecated in 0.3.0. Use caretRightIcon instead. */+ (instancetype)rightDirIcon DEPRECATED_ATTRIBUTE;
/*! @deprecated in 0.3.0. Use chevronDownIcon instead. */+ (instancetype)downOpenIcon DEPRECATED_ATTRIBUTE;
/*! @deprecated in 0.3.0. Use chevronLeftIcon instead. */+ (instancetype)leftOpenIcon DEPRECATED_ATTRIBUTE;
/*! @deprecated in 0.3.0. Use chevronRightIcon instead. */+ (instancetype)rightOpenIcon DEPRECATED_ATTRIBUTE;
/*! @deprecated in 0.3.0. Use chevronUpIcon instead. */+ (instancetype)upOpenIcon DEPRECATED_ATTRIBUTE;
/*! @deprecated in 0.3.0. Use arrowDownIcon instead. */+ (instancetype)downIcon DEPRECATED_ATTRIBUTE;
/*! @deprecated in 0.3.0. Use arrowLeftIcon instead. */+ (instancetype)leftIcon DEPRECATED_ATTRIBUTE;
/*! @deprecated in 0.3.0. Use arrowRightIcon instead. */+ (instancetype)rightIcon DEPRECATED_ATTRIBUTE;
/*! @deprecated in 0.3.0. Use arrowUpIcon instead. */+ (instancetype)upIcon DEPRECATED_ATTRIBUTE;
/*! @deprecated in 0.3.0. Use handRightIcon instead. */+ (instancetype)rightHandIcon DEPRECATED_ATTRIBUTE;
/*! @deprecated in 0.3.0. Use handLeftIcon instead. */+ (instancetype)leftHandIcon DEPRECATED_ATTRIBUTE;
/*! @deprecated in 0.3.0. Use handUpIcon instead. */+ (instancetype)upHandIcon DEPRECATED_ATTRIBUTE;
/*! @deprecated in 0.3.0. Use handDownIcon instead. */+ (instancetype)downHandIcon DEPRECATED_ATTRIBUTE;
/*! @deprecated in 0.3.0. Use circleArrowLeftIcon instead. */+ (instancetype)leftCircledIcon DEPRECATED_ATTRIBUTE;
/*! @deprecated in 0.3.0. Use circleArrowRightIcon instead. */+ (instancetype)rightCircledIcon DEPRECATED_ATTRIBUTE;
/*! @deprecated in 0.3.0. Use circleArrowUpIcon instead. */+ (instancetype)upCircledIcon DEPRECATED_ATTRIBUTE;
/*! @deprecated in 0.3.0. Use circleArrowDownIcon instead. */+ (instancetype)downCircledIcon DEPRECATED_ATTRIBUTE;
/*! @deprecated in 0.3.0. Use repeatIcon instead. */+ (instancetype)cwIcon DEPRECATED_ATTRIBUTE;
/*! @deprecated in 0.3.0. Use undoIcon instead. */+ (instancetype)ccwIcon DEPRECATED_ATTRIBUTE;
/*! @deprecated in 0.3.0. Use refreshIcon instead. */+ (instancetype)arrowsCwIcon DEPRECATED_ATTRIBUTE;
/*! @deprecated in 0.3.0. Use randomIcon instead. */+ (instancetype)shuffleIcon DEPRECATED_ATTRIBUTE;
/*! @deprecated in 0.3.0. Use playCircleIcon instead. */+ (instancetype)playCircle2Icon DEPRECATED_ATTRIBUTE;
/*! @deprecated in 0.3.0. Use stepForwardIcon instead. */+ (instancetype)toEndIcon DEPRECATED_ATTRIBUTE;
/*! @deprecated in 0.3.0. Use fastForwardIcon instead. */+ (instancetype)toEndAltIcon DEPRECATED_ATTRIBUTE;
/*! @deprecated in 0.3.0. Use stepBackwardIcon instead. */+ (instancetype)toStartIcon DEPRECATED_ATTRIBUTE;
/*! @deprecated in 0.3.0. Use fastBackwardIcon instead. */+ (instancetype)toStartAltIcon DEPRECATED_ATTRIBUTE;
/*! @deprecated in 0.3.0. Use forwardIcon instead. */+ (instancetype)fastFwIcon DEPRECATED_ATTRIBUTE;
/*! @deprecated in 0.3.0. Use backwardIcon instead. */+ (instancetype)fastBwIcon DEPRECATED_ATTRIBUTE;
/*! @deprecated in 0.3.0. Use screenshotIcon instead. */+ (instancetype)targetIcon DEPRECATED_ATTRIBUTE;
/*! @deprecated in 0.3.0. Use trophyIcon instead. */+ (instancetype)awardIcon DEPRECATED_ATTRIBUTE;
/*! @deprecated in 0.3.0. Use boltIcon instead. */+ (instancetype)flashIcon DEPRECATED_ATTRIBUTE;
/*! @deprecated in 0.3.0. Use planeIcon instead. */+ (instancetype)flightIcon DEPRECATED_ATTRIBUTE;
/*! @deprecated in 0.3.0. Use listUlIcon instead. */+ (instancetype)listBulletIcon DEPRECATED_ATTRIBUTE;
/*! @deprecated in 0.3.0. Use listOlIcon instead. */+ (instancetype)listNumberedIcon DEPRECATED_ATTRIBUTE;
/*! @deprecated in 0.3.0. Use strikethroughIcon instead. */+ (instancetype)strikeIcon DEPRECATED_ATTRIBUTE;
/*! @deprecated in 0.3.0. Use cutIcon instead. */+ (instancetype)scissorsIcon DEPRECATED_ATTRIBUTE;
/*! @deprecated in 0.3.0. Use adjustIcon instead. */+ (instancetype)ajustIcon DEPRECATED_ATTRIBUTE;
/*! @deprecated in 0.3.0. Use barChartIcon instead. */+ (instancetype)chartBarIcon DEPRECATED_ATTRIBUTE;
/*! @deprecated in 0.3.0. Use saveIcon instead. */+ (instancetype)floppyIcon DEPRECATED_ATTRIBUTE;
/*! @deprecated in 0.3.0. Use bullhornIcon instead. */+ (instancetype)megaphoneIcon DEPRECATED_ATTRIBUTE;
/*! @deprecated in 0.3.0. Use legalIcon instead. */+ (instancetype)hammerIcon DEPRECATED_ATTRIBUTE;
/*! @deprecated in 0.3.0. Use githubSignIcon instead. */+ (instancetype)githubSquaredIcon DEPRECATED_ATTRIBUTE;
/*! @deprecated in 0.3.0. Use twitterSignIcon instead. */+ (instancetype)twitterSquaredIcon DEPRECATED_ATTRIBUTE;
/*! @deprecated in 0.3.0. Use facebookSignIcon instead. */+ (instancetype)facebookSquaredIcon DEPRECATED_ATTRIBUTE;
/*! @deprecated in 0.3.0. Use linkedinSignIcon instead. */+ (instancetype)linkedinSquaredIcon DEPRECATED_ATTRIBUTE;
/*! @deprecated in 0.3.0. Use pinterestIcon instead. */+ (instancetype)pinterestCircledIcon DEPRECATED_ATTRIBUTE;
/*! @deprecated in 0.3.0. Use pinterestSignIcon instead. */+ (instancetype)pinterestSquaredIcon DEPRECATED_ATTRIBUTE;
/*! @deprecated in 0.3.0. Use googlePlusSignIcon instead. */+ (instancetype)gplusSquaredIcon DEPRECATED_ATTRIBUTE;
/*! @deprecated in 0.3.0. Use googlePlusIcon instead. */+ (instancetype)gplusIcon DEPRECATED_ATTRIBUTE;
/*! @deprecated in 0.3.0. Use signBlankIcon instead. */+ (instancetype)blankIcon DEPRECATED_ATTRIBUTE;

@end
