//
//  FIIconicIcon.h
//  FontasticIcons
//
//  Created by Alex Denisov on 17.11.12.
//  Copyright (c) 2013 Alex Denisov. All rights reserved.
//

#import "FIIcon.h"

@interface FIIconicIcon : FIIcon
@end

@interface FIIconicIcon (Forwarding)

+ (instancetype)hashIcon;
+ (instancetype)questionMarkIcon;
+ (instancetype)atIcon;
+ (instancetype)pilcrowIcon;
+ (instancetype)infoIcon;
+ (instancetype)arrowLeftIcon;
+ (instancetype)arrowUpIcon;
+ (instancetype)arrowRightIcon;
+ (instancetype)arrowDownIcon;
+ (instancetype)homeIcon;
+ (instancetype)sunFillIcon;
+ (instancetype)cloudIcon;
+ (instancetype)umbrellaIcon;
+ (instancetype)starIcon;
+ (instancetype)moonFillIcon;
+ (instancetype)heartFillIcon;
+ (instancetype)cogIcon;
+ (instancetype)boltIcon;
+ (instancetype)keyFillIcon;
+ (instancetype)rainIcon;
+ (instancetype)deniedIcon;
+ (instancetype)mailIcon;
+ (instancetype)penIcon;
+ (instancetype)checkIcon;
+ (instancetype)checkAltIcon;
+ (instancetype)xIcon;
+ (instancetype)xAltIcon;
+ (instancetype)leftQuoteIcon;
+ (instancetype)rightQuoteIcon;
+ (instancetype)plusIcon;
+ (instancetype)minusIcon;
+ (instancetype)curvedArrowIcon;
+ (instancetype)documentAltFillIcon;
+ (instancetype)calendarIcon;
+ (instancetype)mapPinAltIcon;
+ (instancetype)commentAlt1FillIcon;
+ (instancetype)commentAlt2FillIcon;
+ (instancetype)penAltFillIcon;
+ (instancetype)penAlt2Icon;
+ (instancetype)chatAltFillIcon;
+ (instancetype)plusAltIcon;
+ (instancetype)minusAltIcon;
+ (instancetype)barsAltIcon;
+ (instancetype)bookAltIcon;
+ (instancetype)apertureAltIcon;
+ (instancetype)beakerAltIcon;
+ (instancetype)leftQuoteAltIcon;
+ (instancetype)rightQuoteAltIcon;
+ (instancetype)arrowLeftAlt1Icon;
+ (instancetype)arrowUpAlt1Icon;
+ (instancetype)arrowRightAlt1Icon;
+ (instancetype)arrowDownAlt1Icon;
+ (instancetype)arrowLeftAlt2Icon;
+ (instancetype)arrowUpAlt2Icon;
+ (instancetype)arrowRightAlt2Icon;
+ (instancetype)arrowDownAlt2Icon;
+ (instancetype)brushIcon;
+ (instancetype)brushAltIcon;
+ (instancetype)eyedropperIcon;
+ (instancetype)layersIcon;
+ (instancetype)layersAltIcon;
+ (instancetype)compassIcon;
+ (instancetype)awardFillIcon;
+ (instancetype)beakerIcon;
+ (instancetype)steeringWheelIcon;
+ (instancetype)eyeIcon;
+ (instancetype)apertureIcon;
+ (instancetype)imageIcon;
+ (instancetype)chartIcon;
+ (instancetype)chartAltIcon;
+ (instancetype)targetIcon;
+ (instancetype)tagFillIcon;
+ (instancetype)rssIcon;
+ (instancetype)rssAltIcon;
+ (instancetype)shareIcon;
+ (instancetype)undoIcon;
+ (instancetype)reloadIcon;
+ (instancetype)reloadAltIcon;
+ (instancetype)loopAlt1Icon;
+ (instancetype)loopAlt2Icon;
+ (instancetype)loopAlt3Icon;
+ (instancetype)loopAlt4Icon;
+ (instancetype)spinIcon;
+ (instancetype)spinAltIcon;
+ (instancetype)moveHorizontalIcon;
+ (instancetype)moveHorizontalAlt1Icon;
+ (instancetype)moveHorizontalAlt2Icon;
+ (instancetype)moveVerticalIcon;
+ (instancetype)moveVerticalAlt1Icon;
+ (instancetype)moveVerticalAlt2Icon;
+ (instancetype)moveIcon;
+ (instancetype)moveAlt1Icon;
+ (instancetype)moveAlt2Icon;
+ (instancetype)transferIcon;
+ (instancetype)downloadIcon;
+ (instancetype)uploadIcon;
+ (instancetype)cloudDownloadIcon;
+ (instancetype)cloudUploadIcon;
+ (instancetype)forkIcon;
+ (instancetype)playIcon;
+ (instancetype)playAltIcon;
+ (instancetype)pauseIcon;
+ (instancetype)stopIcon;
+ (instancetype)ejectIcon;
+ (instancetype)firstIcon;
+ (instancetype)lastIcon;
+ (instancetype)fullscreenIcon;
+ (instancetype)fullscreenAltIcon;
+ (instancetype)fullscreenExitIcon;
+ (instancetype)fullscreenExitAltIcon;
+ (instancetype)equalizerIcon;
+ (instancetype)articleIcon;
+ (instancetype)readMoreIcon;
+ (instancetype)listIcon;
+ (instancetype)listNestedIcon;
+ (instancetype)cursorIcon;
+ (instancetype)dialIcon;
+ (instancetype)windowIcon;
+ (instancetype)trashFillIcon;
+ (instancetype)batteryHalfIcon;
+ (instancetype)batteryEmptyIcon;
+ (instancetype)batteryChargingIcon;
+ (instancetype)chatIcon;
+ (instancetype)micIcon;
+ (instancetype)movieIcon;
+ (instancetype)headphonesIcon;
+ (instancetype)userIcon;
+ (instancetype)lightbulbIcon;
+ (instancetype)cdIcon;
+ (instancetype)folderFillIcon;
+ (instancetype)documentFillIcon;
+ (instancetype)pinIcon;
+ (instancetype)mapPinFillIcon;
+ (instancetype)bookIcon;
+ (instancetype)bookAlt2Icon;
+ (instancetype)boxIcon;
+ (instancetype)calendarAltFillIcon;
+ (instancetype)commentFillIcon;
+ (instancetype)iphoneIcon;
+ (instancetype)barsIcon;
+ (instancetype)cameraIcon;
+ (instancetype)volumeMuteIcon;
+ (instancetype)volumeIcon;
+ (instancetype)batteryFullIcon;
+ (instancetype)magnifyingGlassIcon;
+ (instancetype)lockFillIcon;
+ (instancetype)unlockFillIcon;
+ (instancetype)linkIcon;
+ (instancetype)wrenchIcon;
+ (instancetype)clockIcon;
+ (instancetype)paperclipIcon;

@end
